# Generated by Django 5.2.7 on 2025-11-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('disk', models.TextField(blank=True, null=True, verbose_name='硬盘')),
                ('memory', models.TextField(blank=True, null=True, verbose_name='内存')),
                ('cpu', models.TextField(blank=True, null=True, verbose_name='CPU')),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
